
# Site settings

url: "http://mawie81.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"

# baseurl: /personal-jekyll-theme

google-tracking-id: "UA-68781924-1"

#############
# HTML Head #
#############

author: "Marcel Wiehle"
lang: "en"
title: "{ Marcel Wiehle }"
favicon: "/img/favicon.ico"
description: "frontend developer at http://sprd.net  AG • passionate about @AngularJS and Javascript in general • loves traveling and cooking"
keywords: "personal, javascript, AngularJS"

################
# Intro layout #
################

black-favicon: "/img/black-lab-glass.ico"
me-img: "/img/me.png"

##############################
# Dynamic Text on the header #
##############################

dynamic-typing: True
shuffle: True	# Shuffle the lines.
loop: True
loop-count:	False # Set False for infinite loop, or set any number for finite loop.
type-speed:	10		# Default 10
start-delay: 200	# Default 200
delete-delay: 5000	# Default 5000
lines:			# You can add HTML Tags in the Text
  - text: "The lower you fall, the higher you'll fly."
  - text: "Where’s your will to be weird?"

########
# Blog #
########

post-preview-words: 0

paginate: 5

fb-share: True
twitter-share: True
reddit-share: False
#disqus-shortname: "panossakkos"

###############
# Life Events #
###############

events:
  - image: "/img/career/sprd.png"
    date: "March 2016 - today"
    description: "Senior Frontend Engineer @ <a href='http://www.spreadshirt.net/' target='_blank'>sprd.net AG</a>"
  - image: "/img/career/sprd.png"
    date: "October 2014 - March 2016"
    description: "Frontend Engineer @ <a href='http://www.spreadshirt.net/' target='_blank'>sprd.net AG</a>"
  - image: "/img/career/cpx.png"
    date: "February 2007 - September 2014"
    description: "Software Architect @ <a href='http://www.comparex-group.com/' target='_blank'>COMPAREX AG</a>"
  - image: "/img/career/logo_tu-freiberg.png"
    date: "June 2000 - January 2007"
    description: "M.Sc. Network Computing @ <a href='http://www.tu-freiberg.de/' target='_blank'>TU Bergakademie Freiberg</a>"

# First image of the Career timeline
career-img: "/img/career/default.png"

##################
# Contact layout #
##################

email: "marcel@wiehle.me"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://www.facebook.com/marcel.wiehle.79"
  - title: "twitter"
    url: "https://twitter.com/mwieh81"
  - title: "github"
    url: "https://github.com/mawie81"
  - title: "xing"
    url: "https://www.xing.com/profile/Marcel_Wiehle"
  - title: "linkedin"
    url: "https://de.linkedin.com/pub/marcel-wiehle/44/a78/7ba"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# Tread carefully if you want to change the variables below this point!

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  About: 'about'
  #Blog: 'blog'
  Career: 'career'
  Contact: 'contact'

# Pagination path
paginate_path: "blog/page:num"

# Enable minification SASS
sass:
  style: compressed

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]
